apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 6000
    # Port to forward to inside the pod
    targetPort: 5000
  # type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: sticksword/hello-python:latest
        ports:
        - containerPort: 5000

